image: kkarczmarczyk/node-yarn:7.5-slim

# https://docs.gitlab.com/ce/ci/variables/#predefined-variables-environment-variables

# fetch is faster as it re-uses the project workspace (falling back to clone if it doesn't exist). git clean is used to undo any changes made by the last job, and git fetch is used to retrieve commits made since the last job ran.
variables:
  GIT_STRATEGY: fetch

stages:
  - build
  - test
  - deploy

#
# /api
#

#
# /certs
#

#
# /database
#

#
# /dashboard
#
dashboard-build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/dashboard
    - yarn install

dashboard-test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR/dashboard
    - npm run test

#
# /relay
#
relay-build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/relay
    - yarn install

relay-test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR/relay
    - npm run

#
# /tag
#
tag-build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/tag
    - yarn install
    - npm run build

tag-test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR/tag
    - npm run test

cache:
  paths:
  - tag/node_modules/
  - dashboard/node_modules/
  - relay/node_modules/
