# https://docs.gitlab.com/ce/ci/yaml/
image: kkarczmarczyk/node-yarn:7.5-slim

# https://docs.gitlab.com/ce/ci/variables/#predefined-variables-environment-variables

# fetch is faster as it re-uses the project workspace (falling back to clone if it doesn't exist). git clean is used to undo any changes made by the last job, and git fetch is used to retrieve commits made since the last job ran.
variables:
  GIT_STRATEGY: fetch

stages:
  - build
  - test
  - deploy

#
# /api
#

#
# /certs
#

#
# /dashboard
#
dashboard:build:
  stage: build
  script:
    - npm run dashboard:build
  artifacts:
    expire_in: 1 week
    paths:
    - node_modules

dashboard:test:
  stage: test
  script:
    - npm run dashboard -- test
  dependencies:
    - dashboard:build

#
# /database
#

database:build:
  stage: build
  script:
    - npm run database:build
  artifacts:
    expire_in: 1 week
    paths:
    - node_modules

database:test:
  stage: test
  script:
    - npm run database -- test
  dependencies:
    - database:build


#
# /relay
#
relay:build:
  stage: build
  script:
    - npm run relay:build
  artifacts:
    expire_in: 1 week
    paths:
    - node_modules

relay:test:
  stage: test
  script:
    - npm run relay -- test
  dependencies:
    - relay:build

#
# /tag
#
tag:build:
  stage: build
  script:
    - npm run tag:build
  artifacts:
    expire_in: 1 week
    paths:
    - node_modules

tag:test:
  stage: test
  script:
    - npm run tag -- test
  dependencies:
    - tag:build

cache:
  paths:
  - tag/node_modules/
  - dashboard/node_modules/
  - relay/node_modules/
