# https://docs.gitlab.com/ce/ci/yaml/
image: kkarczmarczyk/node-yarn:7.5-slim

# https://docs.gitlab.com/ce/ci/variables/#predefined-variables-environment-variables

# fetch is faster as it re-uses the project workspace (falling back to clone if it doesn't exist). git clean is used to undo any changes made by the last job, and git fetch is used to retrieve commits made since the last job ran.
variables:
  GIT_STRATEGY: fetch

stages:
  - build
  - test
  - deploy

#
# /api
#

#
# /certs
#

#
# /dashboard
#
dashboard-build:
  stage: build
  script:
    - npm run dashboard:setup

dashboard-test:
  stage: test
  script:
    - npm run dashboard -- test

#
# /database
#

database-build:
  stage: build
  script:
    - npm run database:setup

database-test:
  stage: test
  script:
    - npm run database -- test


#
# /relay
#
relay-build:
  stage: build
  script:
    - npm run relay:setup

relay-test:
  stage: test
  script:
    - npm run relay -- test

#
# /tag
#
tag-build:
  stage: build
  script:
    - npm run tag:setup

tag-test:
  stage: test
  script:
    - npm run tag -- test

cache:
  paths:
  - tag/node_modules/
  - dashboard/node_modules/
  - relay/node_modules/
