apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DATABASE
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_ROOT_PASSWORD
          value: root_password
        - name: POSTGRES_USER
          value: keycloak
        image: postgres
        name: postgres
        resources: {}
      restartPolicy: Always
status: {}
