version: '2'
services:

  server:
    image: jboss/keycloak-postgres:latest
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
