apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kc
  namespace: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak-ha
        image: jboss/keycloak-kubernetes
        imagePullPolicy: Never
        env:
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: mysql.mysql
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: keycloak
        - name: MYSQL_USER
          value: keycloak
        - name: MYSQL_PASSWORD
          value: keycloak
        # first start only, testing only
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: test
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        # TODO
        #- name: CACHE_OWNERS
        #  value: "2"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 9090
        - name: jgroups-tcp
          containerPort: 7600
        - name: jgroups-tcp-fd
          containerPort: 57600
        - name: jgroups-udp
          containerPort: 55200
          protocol: UDP
        - name: jgroups-udp-mc
          containerPort: 45688
          protocol: UDP
        - name: jgroups-udp-fd
          containerPort: 54200
          protocol: UDP
        - name: modcluster
          containerPort: 23364
        - name: modcluster-udp
          containerPort: 23364
          protocol: UDP
        - name: txn-recovery-ev
          containerPort: 4712
        - name: txn-status-mgr
          containerPort: 4713
        readinessProbe:
          httpGet:
            path: /auth/
            port: 8080
