version: '3'

volumes:
  mssql_data:
      driver: local

services:
  mssql:
      image: microsoft/mssql-server-linux:latest
      volumes:
        - mssql_data:/var/lib/mssql
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: P@ssword123
  mssql_setup:
      depends_on:
      - mssql
      image: microsoft/mssql-tools:latest
      command: /bin/bash -c "sleep 8 && /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P P@ssword123 -q 'CREATE DATABASE keycloak;'"
  keycloak:
      image: jboss/keycloak
      build:
        context: ../server
        dockerfile: Dockerfile
      environment:
        DB_ADDR: mssql
        DB_DATABASE: keycloak
        DB_USER: sa
        DB_PASSWORD: P@ssword123
        DB_VENDOR: MSSQL
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - mssql
